#!/usr/bin/env python3
"""
TRAINING AUTOMATION - SCRIPT ALIGNED EDITION
Optimized for the dataset generated by align_samantha_script.py
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path
from rich.console import Console
from rich.prompt import Confirm

console = Console()

class AlignedTrainer:
    def __init__(self):
        self.gpt_sovits_dir = Path("GPT-SoVITS")
        self.dataset_root = Path("samantha_script_dataset")
        self.list_file = self.dataset_root / "filelist.list"
        self.model_name = "Samantha_Ultimate"

    def setup(self):
        if not self.gpt_sovits_dir.exists():
            console.print("[cyan]Cloning GPT-SoVITS...[/cyan]")
            subprocess.run(['git', 'clone', 'https://github.com/RVC-Boss/GPT-SoVITS.git'], check=True)
            
            console.print("[cyan]Installing dependencies...[/cyan]")
            subprocess.run([sys.executable, '-m', 'pip', 'install', '-r', 'GPT-SoVITS/requirements.txt'], check=True)
            
            # Download models
            os.chdir(self.gpt_sovits_dir)
            subprocess.run([sys.executable, 'tools/download_models.py'], check=True)
            os.chdir('..')

    def train(self):
        if not self.list_file.exists():
            console.print("[red]Filelist not found! Run align_samantha_script.py first.[/red]")
            return

        console.print(f"\n[bold green]Starting Training Pipeline for {self.model_name}[/bold green]")
        
        os.chdir(self.gpt_sovits_dir)
        
        # 1. Format Data
        console.print("1. Text Formatting...")
        subprocess.run([
            sys.executable, "GPT_SoVITS/prepare_datasets/1-get-text.py",
            "--inp_text", str(self.list_file.absolute()),
            "--exp_name", self.model_name
        ], check=True)
        
        # 2. Extract Features
        console.print("2. SSL Feature Extraction...")
        subprocess.run([
            sys.executable, "GPT_SoVITS/prepare_datasets/2-get-hubert_wav32k.py",
            "--exp_name", self.model_name
        ], check=True)
        
        console.print("3. Semantic Extraction...")
        subprocess.run([
            sys.executable, "GPT_SoVITS/prepare_datasets/2-get-semantic.py",
            "--exp_name", self.model_name
        ], check=True)
        
        # 3. Train SoVITS (Acoustic)
        console.print("4. Training SoVITS (Timbre)...")
        subprocess.run([
            sys.executable, "GPT_SoVITS/train_s1.py",
            "--exp_name", self.model_name,
            "--batch_size", "8", # RTX 3050 friendly
            "--total_epoch", "15",
            "--save_every_epoch", "5"
        ], check=True)
        
        # 4. Train GPT (Prosody)
        console.print("5. Training GPT (Behavior)...")
        subprocess.run([
            sys.executable, "GPT_SoVITS/train_s2.py",
            "--exp_name", self.model_name,
            "--batch_size", "8",
            "--total_epoch", "10",
            "--save_every_epoch", "5"
        ], check=True)
        
        console.print("[bold green]TRAINING COMPLETE![/bold green]")
        console.print(f"Models are in {self.gpt_sovits_dir}/GPT_weights and SoVITS_weights")

if __name__ == "__main__":
    trainer = AlignedTrainer()
    trainer.setup()
    trainer.train()